# Gradient Descent

In [36]:
import numpy as np

In [37]:
eta = 0.1 # learning rate
n_iterations = 1000
m = 100

np.random.seed(42)
X_b = 2 * np.random.rand(m, 2)
y = 4 + 3 * X_b[:, 0:1] + np.random.randn(m, 1)

theta = np.random.randn(2,1) # random initialization

for iter in range(n_iterations):
    gradients = 2/m * X_b.T.dot(X_b.dot(theta) - y)
    theta = theta - eta * gradients

In [38]:
theta

array([[4.70681619],
       [1.95020596]])

### Stochastic Gradient Descent

In [39]:
n_epochs = 50
t0, t1 = 5, 50 # learning schedule hyperparameters

def learning_schedule(t):
    return t0 / (t + t1)

theta = np.random.randn(2, 1) # random initializations

for epoch in range(n_epochs):
    for i in range(m):
        random_index = np.random.randint(m)
        xi = X_b[random_index:random_index+1]
        yi = y[random_index:random_index+1]
        gradients = 2 * xi.T.dot(xi.dot(theta) - yi)
        eta = learning_schedule(epoch * m + i)
        theta = theta - eta * gradients

In [40]:
theta

array([[4.69012555],
       [1.96516064]])

In [41]:
np.random.seed(42)
X_b = 2 * np.random.rand(m, 2)
y = 4 + 3 * X_b[:, 0:1] + np.random.randn(m, 1)

from sklearn.linear_model import SGDRegressor

reg = SGDRegressor(max_iter=1000, tol=1e-3, penalty=None, eta0=0.1)
reg.fit(X_b, y.ravel())

SGDRegressor(eta0=0.1, penalty=None)

In [42]:
reg.intercept_, reg.coef_

(array([3.78044649]), array([3.21252219, 0.21380922]))